### ISSUE TITLE
Run time failure new download

### ISSUE THREAD

**Issue by Uppermill** [technologiescollege/BlocklyArduino_AIO#1]
![image](https://user-images.githubusercontent.com/18369444/103296190-7e4d3d00-49ed-11eb-80d6-bc894898ee05.png)
I have downloaded version 4.3.2.28 to a Windows 10 PC. I get the error above when I run blocklyArduino_AIO.exe. I tried deleting the .json and .ini files but I still get the same result. I also get a notification
![image](https://user-images.githubusercontent.com/18369444/103296385-e69c1e80-49ed-11eb-9aeb-339affb542a9.png)
Can you help?

**Comment by SebCanet** [comment]
Could you download the release again? I've updated it, I made a mistake with dev & release files....sorry.

**Comment by Uppermill** [comment]
Seb,

Thanks for the fast response.

There are now two files where the path is too long. I skipped over these.

![image](https://user-images.githubusercontent.com/18369444/103367915-28949580-4abe-11eb-8c59-40ca4718b1e2.png)

![image](https://user-images.githubusercontent.com/18369444/103367966-4d890880-4abe-11eb-80c4-199749e9d8ae.png)

I then get this error message

![image](https://user-images.githubusercontent.com/18369444/103368176-d86a0300-4abe-11eb-91e8-eb23bdde1678.png)

I hope these will be helpful.

Allan

**Comment by SebCanet** [comment]
Yeah, on windows there can be problem with this awful structure from Arduino CLI.
You should cut 'BlocklyArduino_AIO-4.3.2.28' folder in C:\BA_AIO\ to minimize the number of characters in path.
You can repair by installing Arduino board tools by yourself:
- open Windows shell in 'C:\BA_AIO\B@electron\arduino' folder, where there is arduino-cli.exe
- delete 'packages' folder
- type 'arduino-cli core install arduino:avr'

For the 2nd problem, did you download my last zip file? [https://github.com/technologiescollege/BlocklyArduino_AIO/releases/download/4.3.2.28/BlocklyArduino_AIO.zip](https://github.com/technologiescollege/BlocklyArduino_AIO/releases/download/4.3.2.28/BlocklyArduino_AIO.zip)

**Comment by Uppermill** [comment]
Seb

That is great - I will try again this afternoon.

I thought I had the right .zip file but I will go through the process again.

Regards

Allan
On 31/12/2020 11:22:28, SebCanet <notifications@github.com> wrote:
Yeah, on windows there can be problem with this awful structure from Arduino CLI.
You should cut 'BlocklyArduino_AIO-4.3.2.28' folder in C:\BA_AIO\ to minimize the number of characters in path.
You can repair by installing Arduino board tools by yourself:
* open Windows shell in 'C:\BA_AIO\B@electron\arduino' folder, where there is arduino-cli.exe
* delete 'packages' folder
* type 'arduino-cli core install arduino:avr'
For the 2nd problem, did you download my last zip file? https://github.com/technologiescollege/BlocklyArduino_AIO/releases/download/4.3.2.28/BlocklyArduino_AIO.zip [https://github.com/technologiescollege/BlocklyArduino_AIO/releases/download/4.3.2.28/BlocklyArduino_AIO.zip]

**Comment by Uppermill** [comment]
Seb

Thanks for your help with this. I renamed the destination file for the unzip and that eliminated the long path name problem.

This time I coan start up the app and I have selected a board successfully.

All looks good - as you thought, I must have used the wrong .zip file.

Thanks again for all your help.

Allan

**Comment by SebCanet** [comment]
Great! Enjoy and success in your tests.
