### ISSUE TITLE
LED Matrix setup block

### ISSUE THREAD

**Issue by cparrapa** [technologiescollege/BlocklyArduino_AIO#1]
Hi 
Great project! i found some little issue in the LED Matrix setup block when i try to compile it lack of ; in the definition for Arduno..

I manage to fix locally is there any special procedure for contributions?

Thanks

**Comment by SebCanet** [comment]
Hi,
thanks for your help. You just have to push your modif, andn I'll add it.

**Comment by cparrapa** [comment]
Hi @SebCanet 

Got it it was a small modification in 
C:\Users\Camilo\Documents\Software\BlocklyArduino_AIO-master\B@electron\www\generators\arduino\sensor_actuator.js

line 106 fixed to:
Blockly.Arduino.definitions_["matrice8x8init"] = "LedControl lc=LedControl(" + din + "," + clk + "," + cs +",1)"+ ';';

once i manage to make more substantial improvements i will push
