### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by Uppermill** [technologiescollege/BlocklyArduino_AIO#2]
Seb

Happy New Year.

I have been trying various combinations for the last 24 hours but I still have not managed to make the software reliably interface with the compiler. I have seen some green compiler messages but I cannot replicate them.

The tmp directory is empty. I tried saving the source as tmp.ino but that did not verify - same problem no messages.

There must be something wrong in the sequence that I am following to to the install. I have documented it here.

Extract .zip to c:\

serial.discovery.exe removed by Norton LifeLock

delete packages folder

in admin powershell
PS C:\BlocklyArduino_AIO\B@electron\arduino> .\arduino-cli core install arduino:avr
Downloading missing tool builtin:ctags@5.8-arduino11...
builtin:ctags@5.8-arduino11 downloaded
Installing builtin:ctags@5.8-arduino11...
builtin:ctags@5.8-arduino11 installed
Downloading missing tool builtin:serial-discovery@1.1.0...
builtin:serial-discovery@1.1.0 downloaded
Installing builtin:serial-discovery@1.1.0...
builtin:serial-discovery@1.1.0 installed
Downloading packages...
arduino:avr-gcc@7.3.0-atmel3.6.1-arduino7 downloaded
arduino:avrdude@6.3.0-arduino17 downloaded
arduino:arduinoOTA@1.3.0 downloaded
arduino:avr@1.8.3 downloaded
Installing arduino:avr-gcc@7.3.0-atmel3.6.1-arduino7...
arduino:avr-gcc@7.3.0-atmel3.6.1-arduino7 installed
Installing arduino:avrdude@6.3.0-arduino17...
arduino:avrdude@6.3.0-arduino17 installed
Installing arduino:arduinoOTA@1.3.0...
arduino:arduinoOTA@1.3.0 installed
Installing arduino:avr@1.8.3...
Configuring platform...
arduino:avr@1.8.3 installed

Norton Lifelock blocks Heur.AdvML.B

run blocklyArduino_AIO.exe

click on top left to change language to English

Click on reset workspace in order to generate the COM selector in the Source Code window

Select Arduino UNO board

Load Project

Select COM24

Save Code

Test Code gives no feedback

Transfer gives a very brief televersement message

![image](https://user-images.githubusercontent.com/18369444/103437749-4af3f380-4c23-11eb-8b08-f811644716ad.png)

Any help would be greatly appreciated.

Allan

**Comment by SebCanet** [comment]
Happy new year too! Hope you will have great moment in your project thanks to my software :-D
Well, what I don't like in your explanation is: "serial.discovery.exe removed by Norton LifeLock" and "Norton Lifelock blocks Heur.AdvML.B". I think it deletes files and block B@AIO.
Serial.discovery.exe is an important file of the arduino-cli package, so when you re install it it deletes it again.
Coud you stop it for a few minutes and just:
- install arduino:avr
- try to compile,
- try to upload in board.
I think it would work.

**Comment by Uppermill** [comment]
I switched off Norton Lifelock, deleted the folders, reinstalled from the .zip file, deleted packages and installed arduino:avr. No Norton messages this time but I still had the same problem. Verify gives no messages and the .tmp directory is empty. Again I tried to save the source to tmp.ino but that made no difference.

Thanks for all your help.

Allan.

**Comment by SebCanet** [comment]
Wow, really weird....I've just tested with the zip and the compile action works, creates a tmp.ino file in \B@electron\arduino\tmp folder, which is the file used by upload.
Could you just test the Blockly@rduino Electron core? Inside 'B@electron' folder, launch 'Blockly@rduino.exe" and test.
Thanks.

**Comment by Uppermill** [comment]
Seb
This time I get an error message. The .ino file is created. Transfer gives the same error message.

![image](https://user-images.githubusercontent.com/18369444/103441399-8bfcff80-4c45-11eb-859e-62381e408784.png)

**Comment by Uppermill** [comment]
Seb

I have downloaded the .zip file onto a Surface Go (my main machine is a Ryzen core desktop machine). I get the same results using the AIO version - no feedback. However the B@electron compiles and downloads to the Arduino.

I hope this helps.

Allan

**Comment by SebCanet** [comment]
I don't understand why B@electron version works and not AIO one... And all my tests on different Windows version work well.
I'll try a different command line for compilation & upload, and send it. But not this week-end, sorry.
News coming soon....

**Comment by Uppermill** [comment]
Seb
I have some further information that might help.
I have discovered that if I follow this sequence, then everything works.

run blocklyArduino_AIO.exe
click on top left to change language to English
Select Arduino UNO board
Load program
Verify
Transfer.

As soon as I click on the the red Reset Workspace button, I can no longer get messages from the compiler.

I had to use the reset button originally to get the drop down box to select COM port. I no longer need to do this as it now seems to identify the COM port (could be that it is because the discovery module is now operational).

So it looks to be a problem with Reset Workspace.

I hope this helps.

Allan

**Comment by SebCanet** [comment]
Strange...in AIO you have to right click on icon in taskbar to change language. How can you " click on top left to change language to English"?
About the reset button, you're right there's a problem. To be sure, which one are you talking about?

**Comment by Uppermill** [comment]
It is this one.

![button](https://user-images.githubusercontent.com/18369444/103667684-29ba3c80-4f6e-11eb-82e7-04b051580d95.png)

Allan

**Comment by Uppermill** [comment]
I click here to change the language.

![image](https://user-images.githubusercontent.com/18369444/103668076-a0efd080-4f6e-11eb-975e-5332553b3086.png)

**Comment by Uppermill** [comment]
Now with oval.

![icon](https://user-images.githubusercontent.com/18369444/103668214-cda3e800-4f6e-11eb-88dd-18b96417a283.png)
